version: '3'

services:
  envoy:
    image: envoyproxy/envoy-alpine:v1.12.1
    command:
      -c /etc/envoy/config.yaml --service-cluster envoy
    volumes:
      - ./configs/:/etc/envoy/:ro
    network_mode: host
