resources:
- "@type": type.googleapis.com/envoy.api.v2.Listener
  name: ingress
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 3000
  filter_chains:
  - filters:
    - name: envoy.http_connection_manager
      config:
        stat_prefix: ingress_http
        route_config:
          virtual_hosts:
          - name: backend
            domains: ["*"]
            routes:
            - match:
                prefix: "/"
              route:
                cluster: service_google
        http_filters:
        - name: envoy.router
          config: {}
